name: Build Wheels

on:
  workflow_dispatch:        # allows manual trigger
  push:
    tags:
      - "v*"                # auto trigger on version tags like v4.0.11

jobs:
  build-windows-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip setuptools wheel build

      - name: Build wheel
        run: |
          python -m build --wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stringzilla-wheels
          path: dist/*.whl
